// This file is auto-generated by @hey-api/openapi-ts

export type User = {
  id: string;
  name: string;
  email: string;
  picture: string;
  createdAt: string;
  updatedAt: string;
};

export type Category = {
  id: string;
  name: string;
  description?: string;
  products?: Array<Product>;
  createdAt: string;
  updatedAt: string;
};

export type Product = {
  id: string;
  name: string;
  description?: string;
  price: number;
  stockQuantity: number;
  category?: Category;
  categoryId: string;
  createdAt: string;
  updatedAt: string;
};

export type Order = {
  id: string;
  user?: User;
  userId: string;
  status: OrderStatus;
  totalAmount: number;
  orderItems?: Array<OrderItem>;
  createdAt: string;
  updatedAt: string;
};

export type OrderItem = {
  id: string;
  orderId: string;
  product?: Product;
  productId: string;
  quantity: number;
  priceAtTime: number;
  createdAt: string;
  updatedAt: string;
};

export type OrderStatus =
  | "PENDING"
  | "PROCESSING"
  | "SHIPPED"
  | "DELIVERED"
  | "CANCELLED";

export type _Error = {
  /**
   * Error message
   */
  error: string;
};

export type GetApiProductsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page number (default: 1)
     */
    page?: number;
    /**
     * Number of items per page (default: 10)
     */
    pageSize?: number;
  };
  url: "/api/products";
};

export type GetApiProductsErrors = {
  /**
   * Internal server error
   */
  500: _Error;
};

export type GetApiProductsError = GetApiProductsErrors[keyof GetApiProductsErrors];

export type GetApiProductsResponses = {
  /**
   * Successful response
   */
  200: {
    data?: Array<Product>;
    page?: number;
    pageSize?: number;
    total?: number;
    totalPages?: number;
  };
};

export type GetApiProductsResponse =
  GetApiProductsResponses[keyof GetApiProductsResponses];

export type PostApiProductsData = {
  body: {
    name: string;
    description?: string;
    price: number;
    stockQuantity: number;
    categoryId: string;
  };
  path?: never;
  query?: never;
  url: "/api/products";
};

export type PostApiProductsErrors = {
  /**
   * Bad request - validation error
   */
  400: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type PostApiProductsError = PostApiProductsErrors[keyof PostApiProductsErrors];

export type PostApiProductsResponses = {
  /**
   * Product created successfully
   */
  201: Product;
};

export type PostApiProductsResponse =
  PostApiProductsResponses[keyof PostApiProductsResponses];

export type GetApiProductsByIdData = {
  body?: never;
  path: {
    /**
     * Product ID
     */
    id: string;
  };
  query?: never;
  url: "/api/products/{id}";
};

export type GetApiProductsByIdErrors = {
  /**
   * Product not found
   */
  404: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type GetApiProductsByIdError =
  GetApiProductsByIdErrors[keyof GetApiProductsByIdErrors];

export type GetApiProductsByIdResponses = {
  /**
   * Product found
   */
  200: Product;
};

export type GetApiProductsByIdResponse =
  GetApiProductsByIdResponses[keyof GetApiProductsByIdResponses];

export type PutApiProductsByIdData = {
  body: {
    name?: string;
    description?: string;
    price?: number;
    stockQuantity?: number;
    categoryId?: string;
  };
  path: {
    /**
     * Product ID
     */
    id: string;
  };
  query?: never;
  url: "/api/products/{id}";
};

export type PutApiProductsByIdErrors = {
  /**
   * Product not found
   */
  404: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type PutApiProductsByIdError =
  PutApiProductsByIdErrors[keyof PutApiProductsByIdErrors];

export type PutApiProductsByIdResponses = {
  /**
   * Product updated successfully
   */
  200: Product;
};

export type PutApiProductsByIdResponse =
  PutApiProductsByIdResponses[keyof PutApiProductsByIdResponses];

export type GetApiCategoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/categories";
};

export type GetApiCategoriesErrors = {
  /**
   * Internal server error
   */
  500: _Error;
};

export type GetApiCategoriesError = GetApiCategoriesErrors[keyof GetApiCategoriesErrors];

export type GetApiCategoriesResponses = {
  /**
   * Successful response
   */
  200: Array<Category>;
};

export type GetApiCategoriesResponse =
  GetApiCategoriesResponses[keyof GetApiCategoriesResponses];

export type PostApiCategoriesData = {
  body: {
    name: string;
    description?: string;
  };
  path?: never;
  query?: never;
  url: "/api/categories";
};

export type PostApiCategoriesErrors = {
  /**
   * Bad request - validation error
   */
  400: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type PostApiCategoriesError =
  PostApiCategoriesErrors[keyof PostApiCategoriesErrors];

export type PostApiCategoriesResponses = {
  /**
   * Category created successfully
   */
  201: Category;
};

export type PostApiCategoriesResponse =
  PostApiCategoriesResponses[keyof PostApiCategoriesResponses];

export type GetApiCategoriesByIdData = {
  body?: never;
  path: {
    /**
     * Category ID
     */
    id: string;
  };
  query?: never;
  url: "/api/categories/{id}";
};

export type GetApiCategoriesByIdErrors = {
  /**
   * Category not found
   */
  404: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type GetApiCategoriesByIdError =
  GetApiCategoriesByIdErrors[keyof GetApiCategoriesByIdErrors];

export type GetApiCategoriesByIdResponses = {
  /**
   * Category found with products
   */
  200: Category;
};

export type GetApiCategoriesByIdResponse =
  GetApiCategoriesByIdResponses[keyof GetApiCategoriesByIdResponses];

export type GetApiOrdersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter orders by user ID
     */
    userId?: string;
  };
  url: "/api/orders";
};

export type GetApiOrdersErrors = {
  /**
   * Internal server error
   */
  500: _Error;
};

export type GetApiOrdersError = GetApiOrdersErrors[keyof GetApiOrdersErrors];

export type GetApiOrdersResponses = {
  /**
   * Successful response
   */
  200: Array<Order>;
};

export type GetApiOrdersResponse = GetApiOrdersResponses[keyof GetApiOrdersResponses];

export type PostApiOrdersData = {
  body: {
    userId: string;
    orderItems: Array<{
      productId: string;
      quantity: number;
    }>;
  };
  path?: never;
  query?: never;
  url: "/api/orders";
};

export type PostApiOrdersErrors = {
  /**
   * Bad request - validation error
   */
  400: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type PostApiOrdersError = PostApiOrdersErrors[keyof PostApiOrdersErrors];

export type PostApiOrdersResponses = {
  /**
   * Order created successfully
   */
  201: Order;
};

export type PostApiOrdersResponse = PostApiOrdersResponses[keyof PostApiOrdersResponses];

export type GetApiOrdersByIdData = {
  body?: never;
  path: {
    /**
     * Order ID
     */
    id: string;
  };
  query?: never;
  url: "/api/orders/{id}";
};

export type GetApiOrdersByIdErrors = {
  /**
   * Order not found
   */
  404: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type GetApiOrdersByIdError = GetApiOrdersByIdErrors[keyof GetApiOrdersByIdErrors];

export type GetApiOrdersByIdResponses = {
  /**
   * Order found with items
   */
  200: Order;
};

export type GetApiOrdersByIdResponse =
  GetApiOrdersByIdResponses[keyof GetApiOrdersByIdResponses];

export type PutApiOrdersByIdStatusData = {
  body: {
    status: OrderStatus;
  };
  path: {
    /**
     * Order ID
     */
    id: string;
  };
  query?: never;
  url: "/api/orders/{id}/status";
};

export type PutApiOrdersByIdStatusErrors = {
  /**
   * Bad request - invalid status
   */
  400: _Error;
  /**
   * Order not found
   */
  404: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type PutApiOrdersByIdStatusError =
  PutApiOrdersByIdStatusErrors[keyof PutApiOrdersByIdStatusErrors];

export type PutApiOrdersByIdStatusResponses = {
  /**
   * Order status updated successfully
   */
  200: Order;
};

export type PutApiOrdersByIdStatusResponse =
  PutApiOrdersByIdStatusResponses[keyof PutApiOrdersByIdStatusResponses];

export type PostApiUsersData = {
  body: {
    name: string;
    email: string;
    password?: string;
    picture?: string;
  };
  path?: never;
  query?: never;
  url: "/api/users";
};

export type PostApiUsersErrors = {
  /**
   * Bad request - validation error
   */
  400: _Error;
  /**
   * Conflict - email already exists
   */
  409: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type PostApiUsersError = PostApiUsersErrors[keyof PostApiUsersErrors];

export type PostApiUsersResponses = {
  /**
   * User created successfully
   */
  201: User;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];

export type GetApiUsersByIdData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type GetApiUsersByIdErrors = {
  /**
   * User not found
   */
  404: _Error;
  /**
   * Internal server error
   */
  500: _Error;
};

export type GetApiUsersByIdError = GetApiUsersByIdErrors[keyof GetApiUsersByIdErrors];

export type GetApiUsersByIdResponses = {
  /**
   * User profile found
   */
  200: User;
};

export type GetApiUsersByIdResponse =
  GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:3000" | "https://api.catalyst.com" | (string & {});
};
