name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest

    env:
      # Public
      ## General
      NEXT_PUBLIC_AUTHORITY: https://catalyst.richardkovacs.dev

      ## Auth
      NEXT_PUBLIC_AUTH_REDIRECT_URL: /dashboard

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      
      - name: Lint project
        run: bun run lint-check && bun run type-check
      
      - name: Build project
        run: bun run build

  contract-tests:
    name: Contract Tests
    runs-on: ubuntu-latest
    needs: build
    
    env:
      DATABASE_URL: "mysql://root:password@localhost:3306/catalyst_test"
      NODE_ENV: test
      NEXT_PUBLIC_AUTHORITY: http://localhost:3000
      AUTH_SECRET: "test-secret-for-contract-testing"

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: catalyst_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Setup database schema
        run: npx prisma db push --force-reset

      - name: Seed test database
        run: npm run seed

      - name: Generate OpenAPI spec
        run: npx @hey-api/openapi-ts -f heyapi.config.ts

      - name: Start API server
        run: |
          npm run build
          npm start &
          echo "Waiting for server to start..."
          sleep 15
          echo "Server should be running on http://localhost:3000"

      - name: Run contract tests
        run: npm run test:contract
        env:
          API_BASE_URL: http://localhost:3000

      - name: Run contract violation tests
        run: npm run test:violations
        env:
          API_BASE_URL: http://localhost:3000
        continue-on-error: true

      - name: Run HeyAPI contract tests
        run: npm run test:heyapi
        env:
          API_BASE_URL: http://localhost:3000
